### ISSUE TITLE
So i made a "static_assets" dataset that screws up validation in many ways...

### ISSUE THREAD

**Issue by angieskazka** [Gapminder/ddf-validation#390]
Here is the dataset i made
https://github.com/open-numbers/ddf--gapminder--static_assets

i am using ddf-validation@1.5.17

consider 2 branched in that dataset

### validation

1) `"id": "WRONG_DATA_POINT_HEADER", "type": "Invalid concept in data point.\n  Raised when header contains a concept based on 'string' type",`

am i not allowed to have strings as datapoints? i should be, see [this](https://github.com/Gapminder/ddf--gapminder--dummy_companies/blob/master/ddf--datapoints--company_size--by--company--anno.csv) for example

2) `"id": "DATA_POINT_WITHOUT_INDICATOR",  "type": "Datapoint without indicator: primary key is equal fields in datapackage.json resource",`

yes, because datapackage is wrong, see below

### datapackage generation
1) ddf--datapoints--income_distribution--by--geo--time.csv: `income_distribution` was included as primary key, while it's an indicator

2) ddfSchema was not generated for datapoints

3) ddfSchema was not generated for entities, that look like this
```
geo
world
```

### validation

1) this is so big, very big, most big ever! i can't even scroll up to know what the problem is  
validator ought to have protection against printing out enormous values, the terminal buffer won't reach the start of the print

2) the actual problem that happened which i don't know

![m6kczsv6m4](https://cloud.githubusercontent.com/assets/3648190/26515096/890e0502-4277-11e7-86a1-0ad4ab6002d7.gif)

**Comment by buchslava** [comment]
@jheeffer @angieskazka

Let me answer the questions:

1. "id": "WRONG_DATA_POINT_HEADER", "type": "Invalid concept in data point.\n Raised when header contains a concept based on 'string' type",

up to you I can discard this rule if needed

2. "id": "DATA_POINT_WITHOUT_INDICATOR", "type": "Datapoint without indicator: primary key is equal fields in datapackage.json resource",

This issue is not reproduced. Perhaps it was fixed by previous commits.

3. datapackage generation

I guess it fixed but I've changed some Jasper's functionality (but I'm not sure that my solution is fully correct):

Jasper, look please at
https://github.com/Gapminder/ddf-validation/blob/fix-complex-datapackage/src/data/ddf-schema.ts#L176
https://github.com/Gapminder/ddf-validation/blob/fix-complex-datapackage/src/data/ddf-schema.ts#L203

these lines related to empty entities section, if you uncomment it, recompile and run datapackage creation then entities section will be empty because in case of `ddf--gapminder--static_assets` we have only one domain without sets that's why 'if (!includes(resource.schema.primaryKey, field))' is always true for entities.

Let's go to chat (tomorrow) if something will be unclear.

4. branch add-topojson

it's ok because jsons in `ddf--gapminder--static_assets` are not valid (single quoted keys and values are denied in json format!) 

You can easy to fix it via `validate-ddf- j`. Angie: be careful with this option until this issue https://github.com/Gapminder/ddf-validation/issues/402 will be resolved (you can revert datapackage.json at least after json fixing)

**Comment by jheeffer** [comment]
3. datapackage generation

I see the issue. ddfSchema has a list of key-value pair but in the case of a 1 column file, there are no values, just the keys. I guess that is a special case, which still should be supported. And it can help answering a query without or with an empty SELECT VALUE clause.

I'll update the ddfSchema on slack and send a PR to this repo.

**Comment by jheeffer** [comment]
@buchslava datapackage.json generation does one thing still not correct. For some reason it assumes that the file

```
ddf--datapoints--income_distribution--by--geo--time.csv
```

has a schema with income_distribution in the primary key, while it should be only `geo` and `time`. So this is not part of ddfSchema creation but one step before: resource schema creation.

```
        {
            "path": "ddf--datapoints--income_distribution--by--geo--time.csv",
            "name": "ddf--datapoints--income_distribution--by--geo--time",
            "schema": {
                "fields": [
                    {
                        "name": "geo"
                    },
                    {
                        "name": "time"
                    },
                    {
                        "name": "income_distribution"
                    }
                ],
                "primaryKey": [
                    "geo",
                    "time",
                    "income_distribution"
                ]
            }
        },
```

**Comment by jheeffer** [comment]
@buchslava it would be nice to know how to easily run datapackage creation from local git repo on a random ddf folder. For testing my solution.
